service: slstspg

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  stage: dev

  lambdaHashingVersion: "20201221"
  runtime: nodejs12.x
  memorySize: 128
  timeout: 3

  # iamRoleStatements:
  #   - permission to call Kms for database creds?
  # environment:
  #   db: get db url

functions:
  hello:
    handler: src/lambdas/handler.hello
    events:
      - http:
          path: /
          method: get
    #add vpc details

resources:
  Resources:
    #database security-group
    #lambda security-group
    postgres:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage:
        DBInstanceClass:
        AllowMajorVersionUpgrade: true|false
        AutoMinorVersionUpgrade: true|false
        AvailabilityZone:
        BackupRetentionPeriod:
        CharacterSetName:
        DBInstanceIdentifier:
        DBName:
        DBParameterGroupName:
        DBSecurityGroups:
          - db-sg-group
        DBSnapshotIdentifier:
        DBSubnetGroupName:
        Engine: mysql|oracle
        EngineVersion:
        Iops:
        KmsKeyId:
        LicenseModel:
        MasterUsername:
        MasterUserPassword:
        MultiAZ: true|false
        OptionGroupName:
        Port:
        PreferredBackupWindow:
        PreferredMaintenanceWindow:
        PubliclyAccessible: true|false
        SourceDBInstanceIdentifier:
        StorageEncrypted: true|false
        StorageType:
        VPCSecurityGroups:
          - vpc-sg-id
        Tags:
          - Key: keyname
            Value: value
