service: slstspg

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  lambdaHashingVersion: "20201221"
  runtime: nodejs12.x
  memorySize: 128
  timeout: 5

  iamRoleStatements:
    - Effect: Allow
      Action: secretsmanager:GetSecretValue
      Resource: ${file(serverless.${self:provider.stage}.yml):postgresSecretArn}
  environment:
    DBSECRET: ${file(serverless.${self:provider.stage}.yml):postgresSecretArn}

functions:
  GetTodayDate:
    handler: src/lambdas/GetTodayDate.handler
    events:
      - http:
          path: /today
          method: get
    vpc:
      subnetIds: ${file(./serverless.${self:provider.stage}.yml):subnets}
      securityGroupIds:
        - !Ref lambdaSecurityGroup

  GetPreviousMonthEnd:
    handler: src/lambdas/GetPreviousMonthEnd.handler
    events:
      - http:
          path: /previousmonth
          method: get
    vpc:
      subnetIds: ${file(./serverless.${self:provider.stage}.yml):subnets}
      securityGroupIds:
        - !Ref lambdaSecurityGroup
resources:
  - ${file(./cfn-resources/rds-resources.yml)}